language: java
sudo: false
addons:
    sonarcloud:
        organization: "tastybento-github"
        token:
            secure: $SONAR_TOKEN
        branches:
            - develop
            - master
jdk:
    - oraclejdk8
    
script:
    - mvn clean verify -P sonar -B
    - echo "${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}"
cache:
    directories:
        - '$HOME/.m2/repository'
        - '$HOME/.sonar/cache'
