language: java
sudo: false
addons:
    sonarcloud:
        organization: "bentobox-world"

jdk:
    - openjdk8
    - openjdk11
    
matrix:
  fast_finish: true
  allow_failures:
    - jdk: openjdk11
        
script:
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install
    - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh && . ./install-jdk.sh -F 11 -L GPL
    - mvn sonar:sonar -Dsonar.projectKey=BentoBoxWorld_BentoBox

cache:
    directories:
        - '$HOME/.m2/repository'
        - '$HOME/.sonar/cache'
