language: java
sudo: false
addons:
    sonarcloud:
        organization: "bentobox-world"

jdk:
    - openjdk8
        
script:
    #- sonar-scanner
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=BentoBoxWorld_BentoBox
    #- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package -P sonar sonar:sonar -B
    #- echo "${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}"
cache:
    directories:
        - '$HOME/.m2/repository'
        - '$HOME/.sonar/cache'
